export const STRINGS = {
  ko: {
    documentTitle: "바운스 업!",
    title: "바운스 업!",
    subtitle: "통통 튀어 하늘 관문까지",
    loading: "게임을 불러오는 중…",
    start: "스페이스 또는 화면을 눌러 시작",
    continue: "스페이스 또는 화면을 눌러 계속",
    controls: "← → / A D 이동 · R 재시작 · M 소리 · Esc 일시정지",
    touchControls: "화면 아래 버튼으로 좌우 이동",
    stage: "스테이지",
    stars: "별",
    time: "시간",
    best: "최고",
    checkpoint: "체크포인트!",
    paused: "일시정지",
    resume: "스페이스 또는 화면을 눌러 계속",
    restartHint: "R을 누르면 현재 스테이지 재시작",
    stageClear: "스테이지 클리어!",
    allClear: "모든 스테이지 클리어!",
    finalMessage: "하늘 관문을 모두 통과했어요!",
    replay: "스페이스 또는 화면을 눌러 다시 플레이",
    soundOn: "소리 켜짐",
    soundOff: "소리 꺼짐",
    died: "앗! 체크포인트에서 다시 시작",
    stageNames: [
      "푸른 언덕",
      "가시 골짜기",
      "스프링 시티",
      "구름 공장",
      "하늘 관문"
    ],
    ariaLeft: "왼쪽으로 이동",
    ariaRight: "오른쪽으로 이동",
    ariaPause: "일시정지",
    ariaSound: "소리 켜기 또는 끄기"
  },
  en: {
    documentTitle: "Bounce Up!",
    title: "Bounce Up!",
    subtitle: "Bounce your way to the sky gate",
    loading: "Loading game…",
    start: "Press Space or tap to start",
    continue: "Press Space or tap to continue",
    controls: "← → / A D move · R restart · M sound · Esc pause",
    touchControls: "Use the lower buttons to move",
    stage: "Stage",
    stars: "Stars",
    time: "Time",
    best: "Best",
    checkpoint: "Checkpoint!",
    paused: "Paused",
    resume: "Press Space or tap to continue",
    restartHint: "Press R to restart this stage",
    stageClear: "Stage Clear!",
    allClear: "All Stages Clear!",
    finalMessage: "You made it through every sky gate!",
    replay: "Press Space or tap to play again",
    soundOn: "Sound on",
    soundOff: "Sound off",
    died: "Oops! Back to the checkpoint",
    stageNames: [
      "Blue Hills",
      "Spike Valley",
      "Spring City",
      "Cloud Factory",
      "Sky Gate"
    ],
    ariaLeft: "Move left",
    ariaRight: "Move right",
    ariaPause: "Pause",
    ariaSound: "Toggle sound"
  }
};

export const STR = STRINGS.ko;
